FM: Fix compilation error [31merror:[0m vendor/qcom/opensource/fm-commonsys/fmapp2/Android.bp:3:1: module FM2 variant android_common: sdk_version: sdk_version must have a value when the module is located at vendor or product(only if PRODUCT_ENFORCE_PRODUCT_PARTITION_INTERFACE is set). [31minternal error:[0m panic in GenerateBuildActions for module FM2 variant android_common rule_builder paths cannot be nil
[31merror:[0m vendor/qcom/opensource/fm-commonsys/fmapp2/Android.bp:10:18: module FM2 variant android_common: platform_apis: This module has conflicting settings. sdk_version is not empty, which means this module cannot use platform APIs. However platform_apis is set to true.